/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * SmartHomeApi
 * Documentation of all Api-Calls the SmartHome Backend can handle.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import * as url from "url";
import * as portableFetch from "portable-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "http://192.168.178.55:5000/v1".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration | undefined;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = portableFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name!: "RequiredError";
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface TemperatureData
 */
export interface TemperatureData {
    /**
     * 
     * @type {number}
     * @memberof TemperatureData
     */
    valueC?: number;
    /**
     * 
     * @type {number}
     * @memberof TemperatureData
     */
    valueF?: number;
}


/**
 * TemperatureApi - fetch parameter creator
 * @export
 */
export const TemperatureApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Gets the last emmited Temperature.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentTemperature(options: any = {}): FetchArgs {
            const localVarPath = `/temperature/getCurrentTemperature`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Emmit a change in the current temperature
         * @param {TemperatureData} body Pet object that needs to be added to the store
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setCurrentTemperature(body: TemperatureData, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling setCurrentTemperature.');
            }
            const localVarPath = `/temperature/setCurrentTemperature`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PUT' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"TemperatureData" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TemperatureApi - functional programming interface
 * @export
 */
export const TemperatureApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Gets the last emmited Temperature.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentTemperature(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<TemperatureData> {
            const localVarFetchArgs = TemperatureApiFetchParamCreator(configuration).getCurrentTemperature(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Emmit a change in the current temperature
         * @param {TemperatureData} body Pet object that needs to be added to the store
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setCurrentTemperature(body: TemperatureData, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = TemperatureApiFetchParamCreator(configuration).setCurrentTemperature(body, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * TemperatureApi - factory interface
 * @export
 */
export const TemperatureApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @summary Gets the last emmited Temperature.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentTemperature(options?: any) {
            return TemperatureApiFp(configuration).getCurrentTemperature(options)(fetch, basePath);
        },
        /**
         * 
         * @summary Emmit a change in the current temperature
         * @param {TemperatureData} body Pet object that needs to be added to the store
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setCurrentTemperature(body: TemperatureData, options?: any) {
            return TemperatureApiFp(configuration).setCurrentTemperature(body, options)(fetch, basePath);
        },
    };
};

/**
 * TemperatureApi - object-oriented interface
 * @export
 * @class TemperatureApi
 * @extends {BaseAPI}
 */
export class TemperatureApi extends BaseAPI {
    /**
     * 
     * @summary Gets the last emmited Temperature.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemperatureApi
     */
    public getCurrentTemperature(options?: any) {
        return TemperatureApiFp(this.configuration).getCurrentTemperature(options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Emmit a change in the current temperature
     * @param {TemperatureData} body Pet object that needs to be added to the store
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemperatureApi
     */
    public setCurrentTemperature(body: TemperatureData, options?: any) {
        return TemperatureApiFp(this.configuration).setCurrentTemperature(body, options)(this.fetch, this.basePath);
    }

}

